---
# tasks file for install-packages
  - name: install {{ pkg_name }} latest version on Ubuntu
    apt:
      name: '{{ pkg_name }}'
      state: latest
    when: ansible_os_family == "Debian"

  - name: install {{ pkg_name }} latest version on Redhat
    yum:
      name: '{{ pkg_name }}'
      state: latest
    when: ansible_os_family == "RedHat"

  - name: start the {{ pkg_name }} service
    service:
      name: '{{ pkg_name }}'
      state: started
